#!/usr/bin/env python3.3

"Sug executable script."

import sys
from sug import sug

if __name__ == "__main__":
    exit(sug.main(sys.argv[1:]))
else:
    raise ImportWarning("This module is a small script that calls main() from"
                        "`sug.sug'.  You probably wanted to import that.")
